### ISSUE TITLE
build failed on automake -a 

### ISSUE THREAD

**Issue by andyyuan78** [benob/icsiboost#3]
ubgpu@ubgpu:~/github/icsiboost$ automake -a
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
Makefile.am: error: required file './README' not found
src/Makefile.am:21: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/Makefile.am:23: warning: source file 'utils/vector.c' is in a subdirectory,
src/Makefile.am:23: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
src/Makefile.am:23: warning: source file 'utils/string.c' is in a subdirectory,
src/Makefile.am:23: but option 'subdir-objects' is disabled
src/Makefile.am:23: warning: source file 'utils/hashtable.c' is in a subdirectory,
src/Makefile.am:23: but option 'subdir-objects' is disabled
src/Makefile.am:23: warning: source file 'utils/array.c' is in a subdirectory,
src/Makefile.am:23: but option 'subdir-objects' is disabled
src/Makefile.am:23: warning: source file 'utils/mapped.c' is in a subdirectory,
src/Makefile.am:23: but option 'subdir-objects' is disabled
src/Makefile.am:23: warning: source file 'utils/threads.c' is in a subdirectory,
src/Makefile.am:23: but option 'subdir-objects' is disabled
src/Makefile.am:23: warning: source file 'utils/debug.c' is in a subdirectory,
src/Makefile.am:23: but option 'subdir-objects' is disabled
src/Makefile.am:23: warning: source file 'utils/file.c' is in a subdirectory,
src/Makefile.am:23: but option 'subdir-objects' is disabled
src/Makefile.am:23: warning: source file 'utils/common.c' is in a subdirectory,
src/Makefile.am:23: but option 'subdir-objects' is disabled
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
ubgpu@ubgpu:~/github/icsiboost$

**Comment by benob** [comment]
configure.in in icsiboost is very old.
Try to reclone it and run ./configure directly.

**Comment by andyyuan78** [comment]
it works.
